//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GunzCord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GunzCord.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan.
        /// </summary>
        public static string CHARACTER_CLAN {
            get {
                return ResourceManager.GetString("CHARACTER_CLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CHARACTER_CREATED {
            get {
                return ResourceManager.GetString("CHARACTER_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string CHARACTER_DEATHS {
            get {
                return ResourceManager.GetString("CHARACTER_DEATHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string CHARACTER_GRADE {
            get {
                return ResourceManager.GetString("CHARACTER_GRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Information.
        /// </summary>
        public static string CHARACTER_INFORMATION {
            get {
                return ResourceManager.GetString("CHARACTER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the character &quot;{0}&quot;.
        /// </summary>
        public static string CHARACTER_INFORMATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("CHARACTER_INFORMATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K/D Ratio.
        /// </summary>
        public static string CHARACTER_KD {
            get {
                return ResourceManager.GetString("CHARACTER_KD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string CHARACTER_KILLS {
            get {
                return ResourceManager.GetString("CHARACTER_KILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Online.
        /// </summary>
        public static string CHARACTER_LAST_ONLINE {
            get {
                return ResourceManager.GetString("CHARACTER_LAST_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string CHARACTER_LEVEL {
            get {
                return ResourceManager.GetString("CHARACTER_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string CHARACTER_SEX {
            get {
                return ResourceManager.GetString("CHARACTER_SEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Played.
        /// </summary>
        public static string CHARACTER_TIME_PLAYED {
            get {
                return ResourceManager.GetString("CHARACTER_TIME_PLAYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        public static string CHARACTER_XP {
            get {
                return ResourceManager.GetString("CHARACTER_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string CLAN_DRAWS {
            get {
                return ResourceManager.GetString("CLAN_DRAWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan Information.
        /// </summary>
        public static string CLAN_INFORMATION {
            get {
                return ResourceManager.GetString("CLAN_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the clan &quot;{0}&quot;.
        /// </summary>
        public static string CLAN_INFORMATION_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLAN_INFORMATION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string CLAN_LEADER {
            get {
                return ResourceManager.GetString("CLAN_LEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan Leaderboard.
        /// </summary>
        public static string CLAN_LEADERBOARD {
            get {
                return ResourceManager.GetString("CLAN_LEADERBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no clan leaderboard, check again tomorrow!.
        /// </summary>
        public static string CLAN_LEADERBOARD_NO_DATA {
            get {
                return ResourceManager.GetString("CLAN_LEADERBOARD_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string CLAN_LOSSES {
            get {
                return ResourceManager.GetString("CLAN_LOSSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string CLAN_POINTS {
            get {
                return ResourceManager.GetString("CLAN_POINTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string CLAN_RANKING {
            get {
                return ResourceManager.GetString("CLAN_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unranked.
        /// </summary>
        public static string CLAN_UNRANKED {
            get {
                return ResourceManager.GetString("CLAN_UNRANKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clan &apos;{0}&apos; has defeated clan &apos;{1}&apos;.
        /// </summary>
        public static string CLAN_WAR_NOTIFICATION_MESSAGE {
            get {
                return ResourceManager.GetString("CLAN_WAR_NOTIFICATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string CLAN_WINS {
            get {
                return ResourceManager.GetString("CLAN_WINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display character information..
        /// </summary>
        public static string COMMANDS_CHARACTER {
            get {
                return ResourceManager.GetString("COMMANDS_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display clan information..
        /// </summary>
        public static string COMMANDS_CLAN {
            get {
                return ResourceManager.GetString("COMMANDS_CLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the top 5 clans..
        /// </summary>
        public static string COMMANDS_CLANRANKING {
            get {
                return ResourceManager.GetString("COMMANDS_CLANRANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this menu..
        /// </summary>
        public static string COMMANDS_HELP {
            get {
                return ResourceManager.GetString("COMMANDS_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string COMMANDS_NAME_PARAMETER {
            get {
                return ResourceManager.GetString("COMMANDS_NAME_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the amount of players online in GunZ..
        /// </summary>
        public static string COMMANDS_ONLINE {
            get {
                return ResourceManager.GetString("COMMANDS_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the server list..
        /// </summary>
        public static string COMMANDS_SERVERINFO {
            get {
                return ResourceManager.GetString("COMMANDS_SERVERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Commands.
        /// </summary>
        public static string COMMANDS_TITLE {
            get {
                return ResourceManager.GetString("COMMANDS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string GRADE_ADMINISTRATOR {
            get {
                return ResourceManager.GetString("GRADE_ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        public static string GRADE_BANNED {
            get {
                return ResourceManager.GetString("GRADE_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Winner.
        /// </summary>
        public static string GRADE_EVENT {
            get {
                return ResourceManager.GetString("GRADE_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Master.
        /// </summary>
        public static string GRADE_GAME_MASTER {
            get {
                return ResourceManager.GetString("GRADE_GAME_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string GRADE_NORMAL {
            get {
                return ResourceManager.GetString("GRADE_NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string HOURS {
            get {
                return ResourceManager.GetString("HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MINUTES {
            get {
                return ResourceManager.GetString("MINUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently {0} players online!.
        /// </summary>
        public static string PLAYERS_ONLINE {
            get {
                return ResourceManager.GetString("PLAYERS_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Information.
        /// </summary>
        public static string SERVER_INFORMATION {
            get {
                return ResourceManager.GetString("SERVER_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} players online.
        /// </summary>
        public static string SERVER_INFORMATION_DETAILS {
            get {
                return ResourceManager.GetString("SERVER_INFORMATION_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string SEX_FEMALE {
            get {
                return ResourceManager.GetString("SEX_FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string SEX_MALE {
            get {
                return ResourceManager.GetString("SEX_MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
    }
}
